# For wasm-bindgen, compiling directly without wasm-pack would require
# us to provide all the autogenerated imports manually.
#
# From now on, let's just stick with wasm-pack.
./build_with_wasm_pack.sh
