[package]
name = "ext_t_calculator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm32-libc = { path = "../../3rd-party/wasm32-libc" }

[build-dependencies]
cc = { workspace = true }
